services:
  trustedge-c2:
    build: ./c2
    container_name: trustedge-c2
    ports:
      - "2321-2322:2321-2322"
    volumes:
      - trustedge-tpm-state:/var/lib/swtpm/tpmstate
    networks:
      - trustedge-network

  trustedge-c4:
    build: ./c4
    container_name: trustedge-c4
    ports:
      - "6080:6080"
    shm_size: "1g"
    networks:
      - trustedge-network

  trustedge-c3:
    build: ./c3
    container_name: trustedge-c3
    environment:
      - TPM2TOOLS_TCTI=swtpm:host=trustedge-c2,port=2321
      - C4_EXEC_URL=http://trustedge-c4:9000/execute
    ports:
      - "8000:8000"
    volumes:
      - trustedge-framework-data:/data
    depends_on:
      - trustedge-c2
      - trustedge-c4
    stdin_open: true
    tty: true
    networks:
      - trustedge-network

  trustedge-c1:
    build: ./c1
    container_name: trustedge-c1
    environment:
      - OLLAMA_MODEL=qwen2.5:7b
      - FRAMEWORK_WS=ws://trustedge-c3:8000/agent-link
    depends_on:
      - trustedge-c3
    stdin_open: true
    tty: true
    networks:
      - trustedge-network

volumes:
  trustedge-tpm-state:
  trustedge-framework-data:

networks:
  trustedge-network:
    driver: bridge

